# Site settings
title: ACIDPINK
feed_title: ACIDPINK
email: chrifpa@gmail.com
description: >



baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acid.pink" # the base hostname & protocol for your site
twitter_username: chrifpa
github_username:  chrifpa
adn_username:     chrifpa
link_char: " ↦"

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "page:num"
